In [45]:
#activar ambiente: ./datos/Scripts/activate
import pandas as pd

Serie de Pandas

In [46]:
numeros= [3,4,5,6,7]
serie= pd.Series(numeros)
serie, type(serie)

(0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64,
 pandas.core.series.Series)

In [47]:
data= {
    "Nombre":["Ana", "Juan","Maria","Pedro","Beyker"],
    "Edad":[22, 25, 28,20,41],
    "Ciudad":["Barcelona","Madrid","Sevilla","Valencia","Zipaquirá"]

}
data, type(data)

({'Nombre': ['Ana', 'Juan', 'Maria', 'Pedro', 'Beyker'],
  'Edad': [22, 25, 28, 20, 41],
  'Ciudad': ['Barcelona', 'Madrid', 'Sevilla', 'Valencia', 'Zipaquirá']},
 dict)

In [48]:
#Generar Data Frame desde diccionario

df= pd.DataFrame(data=data)
df

Nombre  Edad     Ciudad
0     Ana    22  Barcelona
1    Juan    25     Madrid
2   Maria    28    Sevilla
3   Pedro    20   Valencia
4  Beyker    41  Zipaquirá

In [49]:
#Exportar Data Frame (df)
df.to_csv("data.csv")

In [50]:
#Importar un DataFrame
import_df= pd.read_csv("data.csv", index_col=0)
import_df

Nombre  Edad     Ciudad
0     Ana    22  Barcelona
1    Juan    25     Madrid
2   Maria    28    Sevilla
3   Pedro    20   Valencia
4  Beyker    41  Zipaquirá

In [51]:
#Seleccionar Columnas
nombres = df ["Nombre"]
nombres, type(nombres)

(0       Ana
 1      Juan
 2     Maria
 3     Pedro
 4    Beyker
 Name: Nombre, dtype: object,
 pandas.core.series.Series)

In [52]:
# Seleccionar varias columnas
df[["Nombre", "Edad"]]

Nombre  Edad
0     Ana    22
1    Juan    25
2   Maria    28
3   Pedro    20
4  Beyker    41

In [53]:
# Filtrar por indice
fila = df.loc[4]
fila

Nombre       Beyker
Edad             41
Ciudad    Zipaquirá
Name: 4, dtype: object

In [54]:
#Filtrar por condiciones
df[df["Edad"]>23]

Nombre  Edad     Ciudad
1    Juan    25     Madrid
2   Maria    28    Sevilla
4  Beyker    41  Zipaquirá

In [55]:
filtro = (df["Edad"] >23) & (df["Nombre"].str.startswith("B"))
df[filtro]

Nombre  Edad     Ciudad
4  Beyker    41  Zipaquirá

In [56]:
#Filtrar por Query
df.query("Edad < 23")

Nombre  Edad     Ciudad
0    Ana    22  Barcelona
3  Pedro    20   Valencia

In [57]:
df[df["Nombre"].isin(["Ana", "Carlos", "Beyker"])]

Nombre  Edad     Ciudad
0     Ana    22  Barcelona
4  Beyker    41  Zipaquirá

In [58]:
#Con Funcion
def long_5(nombre):
    return len(nombre) == 5
df[df["Nombre"].apply(long_5)]

Nombre  Edad    Ciudad
2  Maria    28   Sevilla
3  Pedro    20  Valencia

In [59]:
# Filtrar entre rangos (inclusivos)
df[df["Edad"].between(25, 45)]

Nombre  Edad     Ciudad
1    Juan    25     Madrid
2   Maria    28    Sevilla
4  Beyker    41  Zipaquirá

In [60]:
df


Nombre  Edad     Ciudad
0     Ana    22  Barcelona
1    Juan    25     Madrid
2   Maria    28    Sevilla
3   Pedro    20   Valencia
4  Beyker    41  Zipaquirá

In [63]:
import numpy as np
import pandas as pd

In [67]:
data= {
    "Nombre":["Ana", "Juan","Maria","Pedro","Beyker"],
    "Edad":[22, 25, np.nan, 20,41],
    "Ciudad":["Barcelona","Madrid","Sevilla",None,"Zipaquirá"]

}

df= pd.DataFrame (data)

In [68]:
df

Nombre  Edad     Ciudad
0     Ana  22.0  Barcelona
1    Juan  25.0     Madrid
2   Maria   NaN    Sevilla
3   Pedro  20.0       None
4  Beyker  41.0  Zipaquirá

In [69]:
#Rellenar faltantes
df_fill= df.fillna (
    {"Edad": df["Edad"].mean(),
    "Ciudad": "Desconocido"
    }
)

df_fill

Nombre  Edad       Ciudad
0     Ana  22.0    Barcelona
1    Juan  25.0       Madrid
2   Maria  27.0      Sevilla
3   Pedro  20.0  Desconocido
4  Beyker  41.0    Zipaquirá

In [70]:
#Eliminar faltantes
df_sin_nulos= df.dropna()
df_sin_nulos

Nombre  Edad     Ciudad
0     Ana  22.0  Barcelona
1    Juan  25.0     Madrid
4  Beyker  41.0  Zipaquirá

In [73]:
#Reemplazar valores
df_reemp=df.replace(
    {
        "Ciudad" : {None:"Deconocido", "Zipaquirá":"Zipa"}
                
    }
)
df_reemp

Nombre  Edad      Ciudad
0     Ana  22.0   Barcelona
1    Juan  25.0      Madrid
2   Maria   NaN     Sevilla
3   Pedro  20.0  Deconocido
4  Beyker  41.0        Zipa

In [78]:
#interpolar
df_interpolado = df.copy()
df_interpolado ["Edad"] = df["Edad"].interpolate ()
df_interpolado


Nombre  Edad     Ciudad
0     Ana  22.0  Barcelona
1    Juan  25.0     Madrid
2   Maria  22.5    Sevilla
3   Pedro  20.0       None
4  Beyker  41.0  Zipaquirá

In [81]:
#Data duplicada
data_duplicada= {
    "Nombre":["Ana", "Juan","Maria","Pedro","Ana","Juan","Beyker"],
    "Edad":[22, 25, np.nan, 20,22, 25, 41],
    "Ciudad":["Barcelona","Madrid","Sevilla",None,"Barcelona","Madrid","Zipaquirá"]
}
df_duplicado= pd.DataFrame(data_duplicada)
df_duplicado


Nombre  Edad     Ciudad
0     Ana  22.0  Barcelona
1    Juan  25.0     Madrid
2   Maria   NaN    Sevilla
3   Pedro  20.0       None
4     Ana  22.0  Barcelona
5    Juan  25.0     Madrid
6  Beyker  41.0  Zipaquirá

In [82]:
df_sin_duplicados = df_duplicado.drop_duplicates()
df_sin_duplicados

Nombre  Edad     Ciudad
0     Ana  22.0  Barcelona
1    Juan  25.0     Madrid
2   Maria   NaN    Sevilla
3   Pedro  20.0       None
6  Beyker  41.0  Zipaquirá

In [113]:
#renombrar Columnas
df_renombrados = df.rename (columns={"Nombre": "Name", "Edad":"Age", "Ciudad":"City"})
df_renombrados

Name   Age       City  Edad_cuadrado
0     Ana  22.0  Barcelona          484.0
1    Juan  25.0     Madrid          625.0
2   Maria   0.0    Sevilla            0.0
3   Pedro  20.0       None          400.0
4  Beyker  41.0  Zipaquirá         1681.0

In [111]:
#Ordenar Columnas
columnas_ordenadas= ["Ciudad", "Edad", "Nombre"]
df_ordenado = df[columnas_ordenadas]
df_ordenado

Ciudad  Edad  Nombre
0  Barcelona  22.0     Ana
1     Madrid  25.0    Juan
2    Sevilla   0.0   Maria
3       None  20.0   Pedro
4  Zipaquirá  41.0  Beyker

In [112]:
#transformacion datos


def cuadrado (x):
    return x**2
df["Edad_cuadrado"]= df["Edad"].apply(cuadrado)
df



Nombre  Edad     Ciudad  Edad_cuadrado
0     Ana  22.0  Barcelona          484.0
1    Juan  25.0     Madrid          625.0
2   Maria   0.0    Sevilla            0.0
3   Pedro  20.0       None          400.0
4  Beyker  41.0  Zipaquirá         1681.0

In [114]:
df

Nombre  Edad     Ciudad  Edad_cuadrado
0     Ana  22.0  Barcelona          484.0
1    Juan  25.0     Madrid          625.0
2   Maria   0.0    Sevilla            0.0
3   Pedro  20.0       None          400.0
4  Beyker  41.0  Zipaquirá         1681.0

In [116]:
data= {
    "Nombre":["Ana", "Juan","Maria","Pedro","Beyker"],
    "Edad":[22, 25, np.nan, 20,41],
    "Ciudad":["Barcelona","Madrid","Sevilla",None,"Zipaquirá"]

}

df= pd.DataFrame (data)
df

Nombre  Edad     Ciudad
0     Ana  22.0  Barcelona
1    Juan  25.0     Madrid
2   Maria   NaN    Sevilla
3   Pedro  20.0       None
4  Beyker  41.0  Zipaquirá

In [124]:
#transformacion datos
edad_promedio=df["Edad"].mean()
df["Edad"].fillna(edad_promedio)
def cuadrado (x):
    return x**2
df["Edad_cuadrado"]= df["Edad"].apply(cuadrado)
df

Nombre  Edad     Ciudad  Edad_cuadrado
0     Ana  22.0  Barcelona          484.0
1    Juan  25.0     Madrid          625.0
2   Maria  27.0    Sevilla          729.0
3   Pedro  20.0       None          400.0
4  Beyker  41.0  Zipaquirá         1681.0

In [125]:
data= {'Nombre':['Juan', 'Ana', 'Luis', 'Laura', 'Pedro', 'Carla'],
'Ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Valencia', 'Barcelona', 'Madrid'],
'Edad':[25, 33, 30, 28, 45,38],
'Puntuación':[80, 90, 85, 88, 75,91]
}

df= pd.DataFrame(data)
df

Nombre     Ciudad  Edad  Puntuación
0   Juan     Madrid    25          80
1    Ana  Barcelona    33          90
2   Luis     Madrid    30          85
3  Laura   Valencia    28          88
4  Pedro  Barcelona    45          75
5  Carla     Madrid    38          91

In [127]:
#Agrupar datos
grouped=df.groupby('Ciudad')
grouped.groups

{'Barcelona': [1, 4], 'Madrid': [0, 2, 5], 'Valencia': [3]}

In [128]:
#Calcular suma edades y puntuaciones por ciudad
aggregated_data=grouped.agg(
    {"Edad": "mean",
    "Puntuación":"sum"

    }
)
aggregated_data

Edad  Puntuación
Ciudad                     
Barcelona  39.0         165
Madrid     31.0         256
Valencia   28.0          88

In [129]:
#Funcion personalizada (Rango= max-min)
def rango(series):
    return series.max() - series.min()

#Aplicar la funcion personalizada
agg_cust= grouped.agg(
    {
        "Edad":rango,
        "Puntuación":rango
    }
)
agg_cust

Edad  Puntuación
Ciudad                     
Barcelona    12          15
Madrid       13          11
Valencia      0           0

In [131]:
#Agrupacion y agregación multi nivel
data["Categoria"]=["A","B","A", "B", "A", "B"]
df= pd.DataFrame(data)
df


Nombre     Ciudad  Edad  Puntuación Categoria
0   Juan     Madrid    25          80         A
1    Ana  Barcelona    33          90         B
2   Luis     Madrid    30          85         A
3  Laura   Valencia    28          88         B
4  Pedro  Barcelona    45          75         A
5  Carla     Madrid    38          91         B

In [132]:
grouped_multi= df.groupby(["Ciudad","Categoria"])
grouped_multi.groups



{('Barcelona', 'A'): [4], ('Barcelona', 'B'): [1], ('Madrid', 'A'): [0, 2], ('Madrid', 'B'): [5], ('Valencia', 'B'): [3]}

In [137]:
#Calcular suma de edades y puntuaciones por Ciudad y Categoria

aggregated_data_multi = grouped_multi.agg (
    {
        "Edad" :"sum",
        "Puntuación" : "mean"
    }
)

aggregated_data_multi

Edad  Puntuación
Ciudad    Categoria                  
Barcelona A            45        75.0
          B            33        90.0
Madrid    A            55        82.5
          B            38        91.0
Valencia  B            28        88.0

In [147]:
#Crear DataFrame de ejemplo

data= {"Nombre":["Juan", "Ana", "Luis", "Laura"],
       "Edad": [25, 33, 30, 28]}
df = pd.DataFrame(data)
df


Nombre  Edad
0   Juan    25
1    Ana    33
2   Luis    30
3  Laura    28

In [148]:
#Agregar Columna
df["Ciudad"] = ["Madrid", "Barcelona", "Madrid", "Valencia"]
df

Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    33  Barcelona
2   Luis    30     Madrid
3  Laura    28   Valencia

In [149]:
#Generamos nueva Fila
new_row= pd.Series ({"Nombre": "Pedro", "Edad": 45, "Ciudad": "Barcelona"})

#Agregamos la fila al df
df= pd.concat ([df, new_row.to_frame().T], ignore_index=True)
df



Nombre Edad     Ciudad
0   Juan   25     Madrid
1    Ana   33  Barcelona
2   Luis   30     Madrid
3  Laura   28   Valencia
4  Pedro   45  Barcelona

In [154]:
#Crear DataFrame de ejemplo

data= {"Nombre":["Juan", "Ana", "Luis", "Laura"],
       "Edad": [25, 33, 30, 28],
       "Ciudad": ["Madrid", "Barcelona", "Madrid", "Valencia"]}
df1 = pd.DataFrame(data)

#Crear 2 DF de ejemplo

data2= {"Nombre":["Carla", "Irene"],
       "Edad": [38, 27],
       "Ciudad": ["Madrid", "Bilbao"]}
df2 = pd.DataFrame(data2)
 

In [155]:
df1

Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    33  Barcelona
2   Luis    30     Madrid
3  Laura    28   Valencia

In [156]:
df2

Nombre  Edad  Ciudad
0  Carla    38  Madrid
1  Irene    27  Bilbao

In [157]:
df_combined=pd.concat ([df1, df2], ignore_index=True)

df_combined

Nombre  Edad     Ciudad
0   Juan    25     Madrid
1    Ana    33  Barcelona
2   Luis    30     Madrid
3  Laura    28   Valencia
4  Carla    38     Madrid
5  Irene    27     Bilbao

In [158]:
#Numpy
import numpy as np

In [160]:
#Arreglo 1 dimension con 5 elementos
arr1 = np.array([1,2,3,4,5,6])
print("Arreglo 1D:", arr1)
print("Forma (shape): ", arr1.shape)
print("Tipo de datos (dtype): ", arr1.dtype)

Arreglo 1D: [1 2 3 4 5 6]
Forma (shape):  (6,)
Tipo de datos (dtype):  int32


In [162]:
#Cambiar forma de arreglo a Matriz 2x3
arr2 = arr1.reshape((2,3)) 
print("Arreglo 2D:\n", arr2)
print("Forma (shape): ", arr2.shape)
print("Tipo de datos (dtype): ", arr2.dtype)

Arreglo 2D:
 [[1 2 3]
 [4 5 6]]
Forma (shape):  (2, 3)
Tipo de datos (dtype):  int32


In [192]:
# Crear matriz 4x4 con numeros aleatorios entre 0 y 1
matrix= np.random.rand(4,4)
print("Arreglo 2D:\n", matrix)
print("Forma (shape): ", matrix.shape)
print("Tipo de datos (dtype): ", matrix.dtype)

Arreglo 2D:
 [[0.55612993 0.18828817 0.80081382 0.77523159]
 [0.5387227  0.93352447 0.34562842 0.28304687]
 [0.2166055  0.99758556 0.7033935  0.02379272]
 [0.37399713 0.8541612  0.69564504 0.98734389]]
Forma (shape):  (4, 4)
Tipo de datos (dtype):  float64


In [195]:
# Crear arreglo 2D a partir de una lista de listas

arr= np.array ([[1,2,3], [4,5,6], [7,8,9]])

print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [196]:
#Crear arreglo de 0 con una forma (3,4)
arr=np.zeros((3,4))
print(arr, type (arr))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'>


In [198]:
#Crear arreglo de 1 con una forma (2,2)
arr=np.ones((2,2))
arr[1,1]=10
print(arr, type (arr))

[[ 1.  1.]
 [ 1. 10.]] <class 'numpy.ndarray'>


In [201]:
#Crear matriz identidad
arr=np.eye(4) #.eye para matriz identidad (diagonal principal son solo 1). El 4 equivale a 4x4
arr 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [211]:
#Crear arreglo 3D de forma (2,3,4)
arr= np.zeros((2,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [213]:
#Transponer
arr=np.random.rand(2,5)
arr

array([[0.71791629, 0.43249121, 0.10482201, 0.10935903, 0.19812545],
       [0.31495911, 0.03502379, 0.73541314, 0.27678773, 0.45880012]])

In [214]:
#Mismo arreglo, pero transpuesto
arr.T

array([[0.71791629, 0.31495911],
       [0.43249121, 0.03502379],
       [0.10482201, 0.73541314],
       [0.10935903, 0.27678773],
       [0.19812545, 0.45880012]])

In [216]:
#Stack
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [217]:
#Concatenar arr Horizontalmente
arr_h=np.hstack((arr1, arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [218]:
#Concatenar arr verticalmente
arr_v=np.vstack((arr1, arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Operaciones Matematicas con Numpy

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
#Calcular suma de elementos
suma = np.sum (arr)
suma

15

In [9]:
#Calcular promedio
promedio = np.mean(arr)
promedio

3.0

In [10]:
#Mediana
mediana= np.median(arr)
mediana

3.0

In [11]:
#Calcular producto
producto=np.prod(arr)
producto

120

In [12]:
#Desviacion estandar
desv_est = np.std(arr)#std es desviacion estandard
desv_est

1.4142135623730951

In [14]:
#Varianza
var=np.var(arr)
var

2.0

In [17]:
#min
min= np.min(arr)
min

#Max
max= np.max(arr)
min, max

(1, 5)

In [19]:
#Suma acumulada
sum_ac= np.cumsum(arr)#cumsum suma acumulada
sum_ac

array([ 1,  3,  6, 10, 15])

In [20]:
#Suma Elemento a elemento (a+a, b+b, c+c...) o Element-Wize
arr + arr

array([ 2,  4,  6,  8, 10])

In [30]:
#Producto Elemento a elemento
arr * arr

array([ 1,  4,  9, 16, 25])